// models/notaEntregaModel.js

const { pool } = require('../db');

const getAllNotasEntrega = async () => {
  const [rows] = await pool.query('SELECT * FROM NOTAENTREGA');
  return rows;
};

const createNotaEntrega = async (notaEntrega) => {
  const {
    FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA,
    PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA,
    IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE,
    NRONOTATRASLADO
  } = notaEntrega;

  const [result] = await pool.query(
    'INSERT INTO NOTAENTREGA (FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
    [FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO]
  );

  return result.insertId;
};

const updateNotaEntrega = async (id, notaEntrega) => {
  const {
    FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA,
    PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA,
    IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE,
    NRONOTATRASLADO
  } = notaEntrega;

  await pool.query(
    'UPDATE NOTAENTREGA SET FECHARECEPCION = ?, HORARECEPCION = ?, FECHAENTREGA = ?, HORAENTREGA = ?, PRECIOESTIMADO = ?, CODIGOCLIENTEENVIA = ?, CODIGOCLIENTERECIBE = ?, IDUSUARIOENVIA = ?, IDUSUARIORECIBE = ?, IDTIPOENVIO = ?, IDESTADOENTREGA = ?, NROREEMBOLSO = ?, CODIGOPAQUETE = ?, NRONOTATRASLADO = ? WHERE NRO = ?',
    [FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO, id]
  );
};

const deleteNotaEntrega = async (id) => {
  await pool.query('DELETE FROM NOTAENTREGA WHERE NRO = ?', [id]);
};

module.exports = {
  getAllNotasEntrega,
  createNotaEntrega,
  updateNotaEntrega,
  deleteNotaEntrega,
};
