// models/notaEntregaModel.js

const { pool } = require('../db');

const getAllNotasEntrega = async () => {
  const [result] = await pool.query('SELECT * FROM NOTAENTREGA');
  return result;
};

const createNotaEntrega = async (notaEntrega) => {
  const {
    NRO, FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA,
    PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE,
    IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA,
    NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO
  } = notaEntrega;

  const [result] = await pool.query(
    'INSERT INTO NOTAENTREGA (NRO, FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
    [NRO, FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO]
  );
  return result;
};

const updateNotaEntrega = async (nro, notaEntrega) => {
  const {
    FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA,
    PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE,
    IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA,
    NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO
  } = notaEntrega;

  const [result] = await pool.query(
    'UPDATE NOTAENTREGA SET FECHARECEPCION = ?, HORARECEPCION = ?, FECHAENTREGA = ?, HORAENTREGA = ?, PRECIOESTIMADO = ?, CODIGOCLIENTEENVIA = ?, CODIGOCLIENTERECIBE = ?, IDUSUARIOENVIA = ?, IDUSUARIORECIBE = ?, IDTIPOENVIO = ?, IDESTADOENTREGA = ?, NROREEMBOLSO = ?, CODIGOPAQUETE = ?, NRONOTATRASLADO = ? WHERE NRO = ?',
    [FECHARECEPCION, HORARECEPCION, FECHAENTREGA, HORAENTREGA, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDUSUARIOENVIA, IDUSUARIORECIBE, IDTIPOENVIO, IDESTADOENTREGA, NROREEMBOLSO, CODIGOPAQUETE, NRONOTATRASLADO, nro]
  );
  return result;
};

const deleteNotaEntrega = async (nro) => {
  const [result] = await pool.query('DELETE FROM NOTAENTREGA WHERE NRO = ?', [nro]);
  return result;
};

const getAllUsuarios = async () => {
  const [result] = await pool.query('SELECT * FROM USUARIO');
  return result;
};

const getAllReembolsos = async () => {
  const [result] = await pool.query('SELECT * FROM REEMBOLSO');
  return result;
};

const getAllNotasTraslado = async () => {
  const [result] = await pool.query('SELECT * FROM NOTATRASLADO');
  return result;
};

module.exports = {
  getAllNotasEntrega,
  createNotaEntrega,
  updateNotaEntrega,
  deleteNotaEntrega,
  getAllUsuarios,
  getAllReembolsos,
  getAllNotasTraslado
};
