const { pool } = require('../db');

const getRecepciones = async () => {
  const [rows] = await pool.query('SELECT * FROM NOTAENTREGA');
  return rows;
};

const getRecepcionByNRO = async (nro) => {
  const [rows] = await pool.query('SELECT * FROM NOTAENTREGA WHERE NRO = ?', [nro]);
  return rows[0];
};

const createRecepcion = async (recepcion) => {
  const { FECHARECEPCION, HORARECEPCION, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDTIPOENVIO, IDESTADOENTREGA, IDUSUARIOENVIA, CODIGOPAQUETE, IDPLANDERUTA } = recepcion;
  const [result] = await pool.query(
    'INSERT INTO NOTAENTREGA (FECHARECEPCION, HORARECEPCION, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDTIPOENVIO, IDESTADOENTREGA, IDUSUARIOENVIA, CODIGOPAQUETE, IDPLANDERUTA) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
    [FECHARECEPCION, HORARECEPCION, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDTIPOENVIO, IDESTADOENTREGA, IDUSUARIOENVIA, CODIGOPAQUETE, IDPLANDERUTA]
  );
  return result;
};

const updateRecepcion = async (nro, recepcion) => {
  const { FECHARECEPCION, HORARECEPCION, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDTIPOENVIO, IDESTADOENTREGA, IDUSUARIOENVIA, CODIGOPAQUETE, IDPLANDERUTA } = recepcion;
  const [result] = await pool.query(
    'UPDATE NOTAENTREGA SET FECHARECEPCION = ?, HORARECEPCION = ?, PRECIOESTIMADO = ?, CODIGOCLIENTEENVIA = ?, CODIGOCLIENTERECIBE = ?, IDTIPOENVIO = ?, IDESTADOENTREGA = ?, IDUSUARIOENVIA = ?, CODIGOPAQUETE = ?, IDPLANDERUTA = ? WHERE NRO = ?',
    [FECHARECEPCION, HORARECEPCION, PRECIOESTIMADO, CODIGOCLIENTEENVIA, CODIGOCLIENTERECIBE, IDTIPOENVIO, IDESTADOENTREGA, IDUSUARIOENVIA, CODIGOPAQUETE, IDPLANDERUTA, nro]
  );
  return result;
};

module.exports = {
  getRecepciones,
  getRecepcionByNRO,
  createRecepcion,
  updateRecepcion
};
